name: flutter_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # di
  get_it: ^7.6.7
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.5
  # hive
  hive: ^2.2.3
  # path
  path_provider: ^2.1.2
  # rest api
  dio: ^5.4.2+1
  dio_retry_plus: ^2.0.6
  # chuck
  chuck_interceptor: ^2.1.2
  # box
  gap: ^3.0.1
  # router
  go_router: ^13.2.2
  # svg
  flutter_svg: ^2.0.10+1
  # url launchers
  url_launcher: ^6.2.5
  # otp autofill
  otp_autofill_plus: ^1.0.3
  # sms autofill
  pin_input_text_field: ^4.5.1
  # package info
  package_info_plus: ^6.0.0
  # cached network image
  cached_network_image: ^3.3.1
  # firebase
  firebase_core: ^2.27.2
  firebase_analytics: ^10.9.0
  firebase_messaging: ^14.7.21
  firebase_remote_config: ^4.3.19
  # local notification
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/locale/
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
